default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: 3306

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  database: chat_system_test

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: 3306
